### ISSUE TITLE
Local hooks check doesn't know about global config

### ISSUE THREAD

**Issue by bengerman13** [cloud-gov/caulking#37]
related to #5 

tl;dr: If I have global hooks enabled, and those global hooks check gitleaks, I _think_ the check for gitleaks in local hooks is unnecessary

One of the tests run by `make audit` looks like this:
- check to see if `.git/hooks/pre-commit` exists in the repo. If not, return success.
- check to see if `.git/hooks/pre-commit` has the string `gitleaks` in a way that doesn't look like a comment. If not, fail.

It seems, on my setup at least, that my global hooks run even when my local hooks don't have `gitleaks` in them (relevant info below)

```console
$ git commit --allow-empty -m "test-commit"
black................................................(no files to check)Skipped
INFO[2020-10-15T10:48:07-07:00] No leaks detected in staged changes
[test-branch 0e419fb] test-commit
$  cat .git/hooks/pre-commit
#!/usr/local/opt/pre-commit/libexec/bin/python3
# File generated by pre-commit: https://pre-commit.com
# ID: 138fd403232d2ddd5efb44317e38bf03
import os
import sys

# we try our best, but the shebang of this script is difficult to determine:
# - macos doesn't ship with python3
# - windows executables are almost always `python.exe`
# therefore we continue to support python2 for this small script
if sys.version_info < (3, 3):
    from distutils.spawn import find_executable as which
else:
    from shutil import which

# work around https://github.com/Homebrew/homebrew-core/issues/30445
os.environ.pop('__PYVENV_LAUNCHER__', None)

# start templated
INSTALL_PYTHON = '/usr/local/opt/pre-commit/libexec/bin/python3'
ARGS = ['hook-impl', '--config=.pre-commit-config.yaml', '--hook-type=pre-commit']
# end templated
ARGS.extend(('--hook-dir', os.path.realpath(os.path.dirname(__file__))))
ARGS.append('--')
ARGS.extend(sys.argv[1:])

DNE = '`pre-commit` not found.  Did you forget to activate your virtualenv?'
if os.access(INSTALL_PYTHON, os.X_OK):
    CMD = [INSTALL_PYTHON, '-mpre_commit']
elif which('pre-commit'):
    CMD = ['pre-commit']
else:
    raise SystemExit(DNE)

CMD.extend(ARGS)
if sys.platform == 'win32':  # https://bugs.python.org/issue19124
    import subprocess

    if sys.version_info < (3, 7):  # https://bugs.python.org/issue25942
        raise SystemExit(subprocess.Popen(CMD).wait())
    else:
        raise SystemExit(subprocess.call(CMD))
else:
    os.execvp(CMD[0], CMD)
$ git config -l
credential.helper=osxkeychain
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
gitseekret.version=1
gitseekret.rulespath=/Users/my_user/.git-support/seekret-rules
gitseekret.rulesenabled=aws.secret_access_key,aws.access_key_id,aws.account_id,mandrill.username,mandrill.password,mandrill.api_key,newrelic.license_key,slack.api_token
gitseekret.exceptionsfile=
hooks.gitleaks=true
core.hookspath=/Users/my_user/.git-support/hooks
pull.ff=only
init.defaultbranch=main
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
core.precomposeunicode=true
remote.origin.url=git@github.com:cloud-gov/external-domain-broker-migrator.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
hooks.gitleaks=true
```

**Comment by pburkholder** [comment]
Yikes - forgot about this.  Sorry you'll have to put up with that error again this quarter.

**Comment by pburkholder** [comment]
@drewbo Here's a pre-exising issue on this.

We do the local checks because the Git documentation on this is quite clear that setting `hookspath` results in the those hooks executing `instead of` the local hooks. 

https://github.com/git/git/blob/master/Documentation/config/core.txt#L499-L504

However, our experience is that the documentation is wrong.

We "should" do the following:

- [ ] submit a PR to Git to correct the documentation (and add tests to https://github.com/git/git/blob/master/t/t1800-hook.sh to confirm this) that, in fact, both sets of hooks are run.
- [ ] Update `check-repos.sh` script to instead check that no local configuration uses a different setting for `hookspath`

We may only get to the second of these two...

**Comment by markdboyd** [comment]
I sent an email to the git mailing list about the possibly inaccurate documentation for core.hooksPath: https://lore.kernel.org/git/CABBKgan9hLme+9WTNNVrZXxqO4-VRGiC3RLQgfKFUHAy3QZvDA@mail.gmail.com/T/#u

**Comment by markdboyd** [comment]
With #89 merged and the question submitted to the git mailing list, I think this issue can be closed, but anyone can feel free to re-open the issue if they see fit
