### ISSUE TITLE
.aws fails false positive? (negative?)

### ISSUE THREAD

**Issue by jadudm** [cloud-gov/caulking#45]
Running `make audit`, I get

```
 ✗ audit fails if AWS keys are in ~/.aws
   (in test file caulked.bats, line 69)
     `[ ${status} -eq 1 ]' failed with status 2
   Initialized empty Git repository in /private/var/folders/8x/vrpz2njj5vv0ls0xtr32_w240000gn/T/gittest.ChNDn1/.git/
```

I don't have a `.aws` directory. At least, I don't think I do. (I can't find one in $HOME.)

I'm wondering if the grep is returning a non-zero code if the directory doesn't exist? Not sure... that's just based on a quick look on my part. 

I don't know that there is anything unique about my setup. Happy to provide more info if it helps.

**Comment by pburkholder** [comment]
This should be fixed in https://github.com/cloud-gov/caulking/commit/8e420939c345466531d9a203015bd8f45882efa0
