### ISSUE TITLE
Simplify caulking installation and upgrades

### ISSUE THREAD

**Issue by tammersaleh** [cloud-gov/caulking#5]
Currently, the `Makefile` system is responsible for creating the `~/.git-support` directory, copying the relevant files into it, and configuring `core.hooksPath` to point at it.  This means we have to remember to run `make install` whenever we pull new changes to this repo, and we have to ensure `make install` is idempotent.

I think it might simplify things if we instead had `make install` create `~/.git-support` as a symlink into the locally cloned copy of this repository, and we embedded the required files directly in here.  That would simplify the installation process, and would make upgrades as easy as `git pull`.

This repo's structure would then look something like:

```
~/workspace/caulking/
├── README.md
├── ...
├── gitleaks.toml
└── hooks
    └── pre-commit
```

...`.git-support` would look like:

```
$HOME/.git-support -> ~/workspace/caulking
```

...and `make install` would run something like:

```
ln -sf "$(dirname "$0")" ~/.git-support
```

Whadayathink?

**Comment by tammersaleh** [comment]
correction:

...and make install would run something like:

``` bash
git config --global core.hooksPath ~/.git-support
ln -sf "$(dirname "$0")" ~/.git-support
```

Thinking about this, we could simplify even further by just having `make install` run:

``` bash
git config --global core.hooksPath "$(dirname "$0")"
```

And getting rid of `~/.git-support` altogether.

**Comment by pburkholder** [comment]
`make patterns` is how we update the config. But I'm always +1 on idempotency. I'll look into it.

**Comment by pburkholder** [comment]
Yeah, I agree this is better. But I'm getting called to go play Gloomhaven, so I'll implement later.

**Comment by onelittlebecca** [comment]
What is the purpose of cleaning up the install? Is it to share it widely for use, or internal facing only?

**Comment by tammersaleh** [comment]
Internal facing only.  The install isn't so bad, but having to run a command on upgrade just seems wasteful.

**Comment by pburkholder** [comment]
I'm taking this off the project planning board because it's not in scope for getting things lined up for 3PAO. I'm instead tracking #24  and #20

**Comment by pburkholder** [comment]
We've iterated on this process in other tickets, and it seems to work pretty smoothly for new and existing team members. Closing.
