### ISSUE TITLE
Pin gitleaks to version 7.6.1 to give us time to update to the 8.x releases (12/21)

### ISSUE THREAD

**Issue by ccostino** [cloud-gov/caulking#56]
A new version of `gitleaks` has been released to bring it to version [`8.0.0`](https://github.com/zricethezav/gitleaks/releases/tag/v8.0.0) (now at [`8.1.1`](https://github.com/zricethezav/gitleaks/releases/tag/v8.1.1) at the time of this writing), which brings some breaking changes with it to our current setup.

Specifically, when I go to commit a series of changes now, `gitleaks` will error out due to an unknown flag, `--unstaged`.  This flag was removed in the newest versions of the tool and appears to have been replaced/incorporated into a new [`protect`](https://github.com/zricethezav/gitleaks#protect) subcommand.

It looks like the line we need to change is [line 17 in our pre-commit shell script](https://github.com/cloud-gov/caulking/blob/master/pre-commit.sh#L17), but I suspect we'll have to do a bit more than just swap a flag with a subcommand.  It looks like some of the flags/options may have changed as well according to the [Usage section of the README in the latest release](https://github.com/zricethezav/gitleaks/tree/v8.1.0#usage).

It also looks like [the new version (`8.1.1`)](https://github.com/zricethezav/gitleaks/releases/tag/v8.1.1) ignores `gitleaks.toml` by default; I'm not sure if this will have any impact, either, since I see it referenced in our script as well.

The alternative is to pin our version again to a known working version for us (I believe that would be [`7.6.1`](https://github.com/zricethezav/gitleaks/releases/tag/v7.6.1) - though it looks like we try and [pin to `7.2.1`](https://github.com/cloud-gov/caulking/blob/master/Makefile#L2)) until we have time to come back to this.

**Comment by bengerman13** [comment]
if we install outside of brew, it'd also mean we can install caulking without admin rights on our machines, which is a huge plus, IMO

**Comment by ccostino** [comment]
`gitleaks` is now at `8.1.1`.

**Comment by ccostino** [comment]
I think I have this mostly worked out for downloading the `7.6.1` release from GitHub, but I am unsure of the checksum or signature checking part.  @pburkholder I can start a draft PR with what I have so far to work off of, or if you have time to pair a bit on this I'd appreciate it.  Thanks!

**Comment by ccostino** [comment]
I did start some preliminary work to get things working with the latest release and I think I figured out that path forward as well, but it looks like a lot of the tests will need to be updated, or some other config option(s) toggled that I missed and am unaware of.

**Comment by ccostino** [comment]
FYI that `gitleaks` has already updated to [`8.2.1`](https://github.com/zricethezav/gitleaks/releases/tag/v8.2.1).

**Comment by ccostino** [comment]
A PR is now in place!  Thanks, @pburkholder.

https://github.com/cloud-gov/caulking/pull/57

**Comment by ccostino** [comment]
PR is merged!  We'll revisit `gitleaks` in the near future to get it fully updated.
