### ISSUE TITLE
Bug: false positive with _removing_ a sensitive line

### ISSUE THREAD

**Issue by tammersaleh** [cloud-gov/caulking#7]
See screenshot below.  Two issues:

1. False positive of `CF_PASSWORD: ((production-cf-password))` (which is fine - not the point of this issue)
2. Caught this secret when it was being _removed_ from the repo (this is the point of this issue).  Can we configure gitleaks to only stop commits that _add_ leaks?

<img width="836" alt="cloud-gov-laptop 2020-03-31 09-50-10" src="https://user-images.githubusercontent.com/2016/78053164-0aceb000-7335-11ea-885d-159d07a02383.png">

**Comment by pburkholder** [comment]
I'm going to close this as it's a pending PR upstream, https://github.com/zricethezav/gitleaks/pull/268,
and I can't do anything in caulking to fix this or expedite (aside from 👍 it upstream, which I've already done).

Reopen if it helps track.

**Comment by pburkholder** [comment]
PS: I've fixed the reporting `password: ((thing))` as a leak. It won't get flagged after this next release.
